import Head from 'next/head';
import LandingPage from '../src/components/LandingPage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Oddaj Rzeczy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <LandingPage />
      </div>
    </>
  )
}
